<?php

namespace Database\Seeders;

use App\Models\JobCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class JobCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Information Technology',
                'slug' => 'information-technology',
                'description' => 'Software development, IT infrastructure, and technical support',
                'icon' => 'computer',
                'color' => '#3498db',
                'is_active' => true,
                'meta_title' => 'IT Jobs | Find Information Technology Careers',
                'meta_description' => 'Browse IT job opportunities in software development, networking, cybersecurity, and more.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Engineering',
                'slug' => 'engineering',
                'description' => 'Civil, mechanical, electrical, and other engineering disciplines',
                'icon' => 'engineering',
                'color' => '#2ecc71',
                'is_active' => true,
                'meta_title' => 'Engineering Jobs | Find Engineering Careers',
                'meta_description' => 'Discover engineering jobs across various disciplines including civil, mechanical, and electrical engineering.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Healthcare',
                'slug' => 'healthcare',
                'description' => 'Medical, nursing, and healthcare administration',
                'icon' => 'medical_services',
                'color' => '#e74c3c',
                'is_active' => true,
                'meta_title' => 'Healthcare Jobs | Find Medical Careers',
                'meta_description' => 'Find healthcare jobs in nursing, medicine, therapy, and healthcare administration.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finance',
                'slug' => 'finance',
                'description' => 'Accounting, banking, investment, and financial services',
                'icon' => 'attach_money',
                'color' => '#f39c12',
                'is_active' => true,
                'meta_title' => 'Finance Jobs | Find Financial Careers',
                'meta_description' => 'Explore finance jobs in accounting, banking, investment management, and financial analysis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marketing',
                'slug' => 'marketing',
                'description' => 'Digital marketing, brand management, and market research',
                'icon' => 'campaign',
                'color' => '#9b59b6',
                'is_active' => true,
                'meta_title' => 'Marketing Jobs | Find Marketing Careers',
                'meta_description' => 'Discover marketing jobs in digital marketing, content creation, SEO, and brand management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sales',
                'slug' => 'sales',
                'description' => 'B2B sales, retail, and business development',
                'icon' => 'trending_up',
                'color' => '#34495e',
                'is_active' => true,
                'meta_title' => 'Sales Jobs | Find Sales Careers',
                'meta_description' => 'Browse sales jobs in B2B, retail, account management, and business development.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Human Resources',
                'slug' => 'human-resources',
                'description' => 'Recruitment, HR management, and employee relations',
                'icon' => 'people',
                'color' => '#16a085',
                'is_active' => true,
                'meta_title' => 'HR Jobs | Find Human Resources Careers',
                'meta_description' => 'Explore HR jobs in recruitment, talent management, compensation, and employee relations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Education',
                'slug' => 'education',
                'description' => 'Teaching, training, and educational administration',
                'icon' => 'school',
                'color' => '#27ae60',
                'is_active' => true,
                'meta_title' => 'Education Jobs | Find Teaching Careers',
                'meta_description' => 'Find education jobs in teaching, administration, curriculum development, and training.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legal',
                'slug' => 'legal',
                'description' => 'Law practice, legal counsel, and compliance',
                'icon' => 'gavel',
                'color' => '#7f8c8d',
                'is_active' => true,
                'meta_title' => 'Legal Jobs | Find Law Careers',
                'meta_description' => 'Discover legal jobs in law firms, corporate legal departments, and compliance roles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Administrative',
                'slug' => 'administrative',
                'description' => 'Office management, executive assistance, and administrative support',
                'icon' => 'business_center',
                'color' => '#95a5a6',
                'is_active' => true,
                'meta_title' => 'Administrative Jobs | Find Office Careers',
                'meta_description' => 'Browse administrative jobs in office management, executive assistance, and clerical roles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Customer Service',
                'slug' => 'customer-service',
                'description' => 'Customer support, client relations, and service delivery',
                'icon' => 'support_agent',
                'color' => '#3498db',
                'is_active' => true,
                'meta_title' => 'Customer Service Jobs | Find Support Careers',
                'meta_description' => 'Find customer service jobs in support, client relations, and service delivery.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Design',
                'slug' => 'design',
                'description' => 'Graphic design, UX/UI, and creative services',
                'icon' => 'palette',
                'color' => '#e67e22',
                'is_active' => true,
                'meta_title' => 'Design Jobs | Find Creative Careers',
                'meta_description' => 'Explore design jobs in graphic design, UX/UI, product design, and creative services.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manufacturing',
                'slug' => 'manufacturing',
                'description' => 'Production, quality control, and manufacturing operations',
                'icon' => 'precision_manufacturing',
                'color' => '#1abc9c',
                'is_active' => true,
                'meta_title' => 'Manufacturing Jobs | Find Production Careers',
                'meta_description' => 'Discover manufacturing jobs in production, quality control, and operations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Logistics',
                'slug' => 'logistics',
                'description' => 'Supply chain, transportation, and inventory management',
                'icon' => 'local_shipping',
                'color' => '#d35400',
                'is_active' => true,
                'meta_title' => 'Logistics Jobs | Find Supply Chain Careers',
                'meta_description' => 'Browse logistics jobs in supply chain, transportation, and inventory management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hospitality',
                'slug' => 'hospitality',
                'description' => 'Hotel, restaurant, and tourism services',
                'icon' => 'hotel',
                'color' => '#c0392b',
                'is_active' => true,
                'meta_title' => 'Hospitality Jobs | Find Tourism Careers',
                'meta_description' => 'Find hospitality jobs in hotels, restaurants, tourism, and event management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Retail',
                'slug' => 'retail',
                'description' => 'Store management, merchandising, and retail operations',
                'icon' => 'storefront',
                'color' => '#8e44ad',
                'is_active' => true,
                'meta_title' => 'Retail Jobs | Find Store Careers',
                'meta_description' => 'Explore retail jobs in store management, merchandising, and sales.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Construction',
                'slug' => 'construction',
                'description' => 'Building, architecture, and construction management',
                'icon' => 'construction',
                'color' => '#f1c40f',
                'is_active' => true,
                'meta_title' => 'Construction Jobs | Find Building Careers',
                'meta_description' => 'Discover construction jobs in building, architecture, and project management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Media',
                'slug' => 'media',
                'description' => 'Journalism, broadcasting, and content creation',
                'icon' => 'video_library',
                'color' => '#2980b9',
                'is_active' => true,
                'meta_title' => 'Media Jobs | Find Journalism Careers',
                'meta_description' => 'Browse media jobs in journalism, broadcasting, film, and content creation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Science',
                'slug' => 'science',
                'description' => 'Research, laboratory work, and scientific analysis',
                'icon' => 'science',
                'color' => '#2c3e50',
                'is_active' => true,
                'meta_title' => 'Science Jobs | Find Research Careers',
                'meta_description' => 'Find science jobs in research, laboratory work, and scientific analysis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nonprofit',
                'slug' => 'nonprofit',
                'description' => 'Charity, NGO, and social service organizations',
                'icon' => 'volunteer_activism',
                'color' => '#27ae60',
                'is_active' => true,
                'meta_title' => 'Nonprofit Jobs | Find Charity Careers',
                'meta_description' => 'Explore nonprofit jobs in charities, NGOs, and social service organizations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($categories as $category) {
            JobCategory::create($category);
        }
    }
}

