<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'value' => 'JobPortal',
                'group' => 'general',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_tagline',
                'value' => 'Find Your Dream Job',
                'group' => 'general',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_description',
                'value' => 'A comprehensive job portal connecting employers with talented professionals',
                'group' => 'general',
                'type' => 'textarea',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_logo',
                'value' => '/images/logo.png',
                'group' => 'general',
                'type' => 'file',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'favicon',
                'value' => '/images/favicon.ico',
                'group' => 'general',
                'type' => 'file',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'admin_email',
                'value' => 'admin@jobportal.com',
                'group' => 'general',
                'type' => 'email',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'support_email',
                'value' => 'support@jobportal.com',
                'group' => 'general',
                'type' => 'email',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_language',
                'value' => 'en',
                'group' => 'general',
                'type' => 'select',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_timezone',
                'value' => 'UTC',
                'group' => 'general',
                'type' => 'select',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'date_format',
                'value' => 'Y-m-d',
                'group' => 'general',
                'type' => 'select',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'time_format',
                'value' => 'H:i',
                'group' => 'general',
                'type' => 'select',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Contact Information
            [
                'key' => 'company_name',
                'value' => 'JobPortal Inc.',
                'group' => 'contact',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'company_address',
                'value' => '123 Employment Avenue, Career City, JB 12345',
                'group' => 'contact',
                'type' => 'textarea',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'company_phone',
                'value' => '+1 (555) 123-4567',
                'group' => 'contact',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'company_email',
                'value' => 'info@jobportal.com',
                'group' => 'contact',
                'type' => 'email',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Social Media
            [
                'key' => 'facebook_url',
                'value' => 'https://facebook.com/jobportal',
                'group' => 'social',
                'type' => 'url',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/jobportal',
                'group' => 'social',
                'type' => 'url',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'linkedin_url',
                'value' => 'https://linkedin.com/company/jobportal',
                'group' => 'social',
                'type' => 'url',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://instagram.com/jobportal',
                'group' => 'social',
                'type' => 'url',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Email Settings
            [
                'key' => 'mail_driver',
                'value' => 'smtp',
                'group' => 'email',
                'type' => 'select',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_host',
                'value' => 'smtp.mailtrap.io',
                'group' => 'email',
                'type' => 'text',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_port',
                'value' => '2525',
                'group' => 'email',
                'type' => 'text',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_username',
                'value' => 'username',
                'group' => 'email',
                'type' => 'text',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_password',
                'value' => 'password',
                'group' => 'email',
                'type' => 'password',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_encryption',
                'value' => 'tls',
                'group' => 'email',
                'type' => 'select',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@jobportal.com',
                'group' => 'email',
                'type' => 'email',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_from_name',
                'value' => 'JobPortal',
                'group' => 'email',
                'type' => 'text',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Job Settings
            [
                'key' => 'jobs_per_page',
                'value' => '20',
                'group' => 'jobs',
                'type' => 'number',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'featured_jobs_limit',
                'value' => '6',
                'group' => 'jobs',
                'type' => 'number',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'job_expiry_days',
                'value' => '30',
                'group' => 'jobs',
                'type' => 'number',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'enable_job_approval',
                'value' => 'true',
                'group' => 'jobs',
                'type' => 'boolean',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'allow_job_editing',
                'value' => 'true',
                'group' => 'jobs',
                'type' => 'boolean',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_job_status',
                'value' => 'pending',
                'group' => 'jobs',
                'type' => 'select',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // User Settings
            [
                'key' => 'enable_user_registration',
                'value' => 'true',
                'group' => 'users',
                'type' => 'boolean',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'require_email_verification',
                'value' => 'true',
                'group' => 'users',
                'type' => 'boolean',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'allow_social_login',
                'value' => 'true',
                'group' => 'users',
                'type' => 'boolean',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_user_role',
                'value' => 'candidate',
                'group' => 'users',
                'type' => 'select',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Payment Settings
            [
                'key' => 'currency',
                'value' => 'USD',
                'group' => 'payment',
                'type' => 'select',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'currency_symbol',
                'value' => '$',
                'group' => 'payment',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'stripe_public_key',
                'value' => 'pk_test_example',
                'group' => 'payment',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'stripe_secret_key',
                'value' => 'sk_test_example',
                'group' => 'payment',
                'type' => 'password',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'paypal_client_id',
                'value' => 'client_id_example',
                'group' => 'payment',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'paypal_secret',
                'value' => 'secret_example',
                'group' => 'payment',
                'type' => 'password',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'paypal_mode',
                'value' => 'sandbox',
                'group' => 'payment',
                'type' => 'select',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // SEO Settings
            [
                'key' => 'meta_title',
                'value' => 'JobPortal - Find Your Dream Job',
                'group' => 'seo',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_description',
                'value' => 'JobPortal connects job seekers with employers. Find your dream job or hire top talent today.',
                'group' => 'seo',
                'type' => 'textarea',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_keywords',
                'value' => 'jobs, career, employment, hiring, job search',
                'group' => 'seo',
                'type' => 'textarea',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'google_analytics_id',
                'value' => 'UA-XXXXX-Y',
                'group' => 'seo',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'enable_sitemap',
                'value' => 'true',
                'group' => 'seo',
                'type' => 'boolean',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Security Settings
            [
                'key' => 'recaptcha_site_key',
                'value' => 'site_key_example',
                'group' => 'security',
                'type' => 'text',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'recaptcha_secret_key',
                'value' => 'secret_key_example',
                'group' => 'security',
                'type' => 'password',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'enable_recaptcha',
                'value' => 'true',
                'group' => 'security',
                'type' => 'boolean',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'max_login_attempts',
                'value' => '5',
                'group' => 'security',
                'type' => 'number',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'password_reset_timeout',
                'value' => '60',
                'group' => 'security',
                'type' => 'number',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($settings as $setting) {
            Setting::create($setting);
        }
    }
}

