<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            // Technical Skills
            [
                'name' => 'JavaScript',
                'slug' => 'javascript',
                'category' => 'Technical',
                'description' => 'Programming language for web development',
                'icon' => 'code',
                'color' => '#f7df1e',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Python',
                'slug' => 'python',
                'category' => 'Technical',
                'description' => 'Programming language for various applications',
                'icon' => 'code',
                'color' => '#3776ab',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Java',
                'slug' => 'java',
                'category' => 'Technical',
                'description' => 'Object-oriented programming language',
                'icon' => 'code',
                'color' => '#007396',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'C#',
                'slug' => 'c-sharp',
                'category' => 'Technical',
                'description' => 'Programming language for .NET framework',
                'icon' => 'code',
                'color' => '#68217a',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PHP',
                'slug' => 'php',
                'category' => 'Technical',
                'description' => 'Server-side scripting language',
                'icon' => 'code',
                'color' => '#777bb4',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SQL',
                'slug' => 'sql',
                'category' => 'Technical',
                'description' => 'Database query language',
                'icon' => 'storage',
                'color' => '#e48e00',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'React',
                'slug' => 'react',
                'category' => 'Technical',
                'description' => 'JavaScript library for building user interfaces',
                'icon' => 'code',
                'color' => '#61dafb',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angular',
                'slug' => 'angular',
                'category' => 'Technical',
                'description' => 'TypeScript-based web application framework',
                'icon' => 'code',
                'color' => '#dd0031',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vue.js',
                'slug' => 'vue-js',
                'category' => 'Technical',
                'description' => 'JavaScript framework for building user interfaces',
                'icon' => 'code',
                'color' => '#42b883',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Node.js',
                'slug' => 'node-js',
                'category' => 'Technical',
                'description' => 'JavaScript runtime environment',
                'icon' => 'code',
                'color' => '#339933',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AWS',
                'slug' => 'aws',
                'category' => 'Technical',
                'description' => 'Amazon Web Services cloud platform',
                'icon' => 'cloud',
                'color' => '#ff9900',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Docker',
                'slug' => 'docker',
                'category' => 'Technical',
                'description' => 'Containerization platform',
                'icon' => 'dns',
                'color' => '#2496ed',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kubernetes',
                'slug' => 'kubernetes',
                'category' => 'Technical',
                'description' => 'Container orchestration system',
                'icon' => 'dns',
                'color' => '#326ce5',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Git',
                'slug' => 'git',
                'category' => 'Technical',
                'description' => 'Version control system',
                'icon' => 'merge_type',
                'color' => '#f05032',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DevOps',
                'slug' => 'devops',
                'category' => 'Technical',
                'description' => 'Development and operations integration',
                'icon' => 'settings',
                'color' => '#0db7ed',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Soft Skills
            [
                'name' => 'Communication',
                'slug' => 'communication',
                'category' => 'Soft',
                'description' => 'Effective verbal and written communication',
                'icon' => 'chat',
                'color' => '#3498db',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leadership',
                'slug' => 'leadership',
                'category' => 'Soft',
                'description' => 'Ability to guide and motivate teams',
                'icon' => 'supervisor_account',
                'color' => '#2ecc71',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Problem Solving',
                'slug' => 'problem-solving',
                'category' => 'Soft',
                'description' => 'Analytical thinking and solution development',
                'icon' => 'psychology',
                'color' => '#e74c3c',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teamwork',
                'slug' => 'teamwork',
                'category' => 'Soft',
                'description' => 'Collaboration and cooperation with others',
                'icon' => 'groups',
                'color' => '#f39c12',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Time Management',
                'slug' => 'time-management',
                'category' => 'Soft',
                'description' => 'Efficient use of time and prioritization',
                'icon' => 'schedule',
                'color' => '#9b59b6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Business Skills
            [
                'name' => 'Project Management',
                'slug' => 'project-management',
                'category' => 'Business',
                'description' => 'Planning, executing, and closing projects',
                'icon' => 'assignment',
                'color' => '#34495e',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marketing',
                'slug' => 'marketing',
                'category' => 'Business',
                'description' => 'Promotion and selling of products or services',
                'icon' => 'campaign',
                'color' => '#16a085',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sales',
                'slug' => 'sales',
                'category' => 'Business',
                'description' => 'Direct selling and customer acquisition',
                'icon' => 'trending_up',
                'color' => '#27ae60',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Financial Analysis',
                'slug' => 'financial-analysis',
                'category' => 'Business',
                'description' => 'Evaluation of financial data and trends',
                'icon' => 'attach_money',
                'color' => '#7f8c8d',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data Analysis',
                'slug' => 'data-analysis',
                'category' => 'Business',
                'description' => 'Interpretation of data for business insights',
                'icon' => 'analytics',
                'color' => '#95a5a6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($skills as $skill) {
            Skill::create($skill);
        }
    }
}

